name: flutter_jsh_v2
description: JSH V2

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  freezed_annotation: ^2.0.1

  flutter_cached_pdfview: ^0.4.1 # PDF Reader
  youtube_player_iframe: ^2.2.2 # Youtube Player
  url_launcher: ^6.1.0 # URL Launcher
  http: ^0.13.4 # http
  flutter_inappwebview: ^5.4.2 # WebView
  shimmer: ^2.0.0 # Shimmer Animation
  card_swiper: ^2.0.3 # Swiper

  # flutter_ios_document_scanner:
  #   git:
  #     url: https://github.com/111coding/flutter_ios_document_scanner
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # flutter pub run build_runner watch --delete-conflicting-outputs
  freezed: ^2.0.2
  build_runner:
  # .g.dart dependency
  json_serializable:

  # https://pub.dev/packages/flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Noto_Sans_KR
      fonts:
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900
          
    - family: Spoqa
      fonts:
        - asset: fonts/spoqa/SpoqaHanSansNeo-Thin.ttf
          weight: 100
        - asset: fonts/spoqa/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: fonts/spoqa/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: fonts/spoqa/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: fonts/spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 700